server:
  port: 8080
  
spring: 
  thymeleaf:
    enabled: true
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://gsitm-intern2020.c5tdqadv8vmd.ap-northeast-2.rds.amazonaws.com/it1455
    username: it1455
    password: it1455
    
mybatis:
  config-location: classpath:sqlmap/sqlmap-config.xml
  mapper-locations: classpath*:sqlmap/mappers/**/*.xml
  type-aliases-package: com.gsitm.career